# Generated by Django 3.2.23 on 2023-12-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='subject',
        ),
    ]
