# Generated by Django 4.1 on 2024-02-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
