# Generated by Django 4.1 on 2024-03-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='question',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
