# Generated by Django 4.1 on 2024-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0003_remove_userprofile_reputation_reputationpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(help_text='Enter a subject line for your question.', max_length=200, unique=True),
        ),
    ]
