# Generated by Django 3.2.23 on 2023-12-31 19:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0003_auto_20231231_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
