# Generated by Django 4.1 on 2024-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0004_alter_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
