# Generated by Django 3.2.23 on 2023-12-31 20:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0004_alter_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='excerpt',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
