# Generated by Django 4.1 on 2024-03-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0005_userprofile_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answercount',
        ),
    ]
