# Generated by Django 4.1 on 2024-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0006_remove_answer_answercount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='name',
        ),
        migrations.AlterField(
            model_name='answer',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
