# Generated by Django 3.2.23 on 2024-01-04 21:52

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0006_answer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='excerpt',
            field=django_quill.fields.QuillField(),
        ),
    ]
