# Generated by Django 3.2.23 on 2024-01-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0007_auto_20240104_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='standards',
        ),
        migrations.AddField(
            model_name='question',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='main_forum.teachingstandardtag'),
        ),
    ]
