# Generated by Django 4.1 on 2024-03-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0007_remove_answer_email_remove_answer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
