# Generated by Django 3.2.23 on 2024-01-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0008_auto_20240110_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='net_votes',
            field=models.IntegerField(default=0),
        ),
    ]
