# Generated by Django 4.1 on 2024-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_forum', '0009_question_net_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='body',
        ),
        migrations.RemoveField(
            model_name='question',
            name='standard',
        ),
        migrations.DeleteModel(
            name='TeachingStandardTag',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='main_forum.tag'),
        ),
    ]
